spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/kuklyasha
    username: kuklyasha
    password: kuklyasha
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600

logging:
  level:
    root: WARN
    ru.serji.kuklyasha: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.security: DEBUG
  file:
    name: log/latest.log

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

upload:
  images:
    path: doll-images
  content:
    allowed-types: image/png, image/jpg

jwt:
  token:
    secret: bigsecret
    expired: 3600000