export const MAIN_ROUTE = "/"
export const CATALOG_ROUTE = "/catalog"
export const DOLL_ROUTE = "/dolls"
export const ABOUT_US_ROUTE = "/about"
export const LOGIN_ROUTE = "/auth/login"
export const PROFILE_ROUTE = "/auth/profile"
export const REGISTRATION_ROUTE = "/auth/registration"