export const CATALOG_ROUTE = "/"
export const DOLL_ROUTE = "/dolls"
export const LOGIN_ROUTE = "/auth/login"
export const PROFILE_ROUTE = "/auth/profile"
export const REGISTRATION_ROUTE = "/auth/registration"